---
- name: Update and Upgrade Ubuntu Servers
  hosts: servers
  become: yes   # This is used to escalate privileges (sudo)

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes
        autoremove: yes   # Remove unnecessary packages
        autoclean: yes    # Clean up package cache
